# Generated by Django 4.1.7 on 2023-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(to='persona.hobby'),
        ),
    ]
