# Generated by Django 4.1.5 on 2023-01-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_autores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
